enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

cli-source = "MorpheApp/morphe-desktop"
cli-version = "dev"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
rv-brand = "ReVanced Extended"
build-mode = "both"
# version = "20.51.39"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/crimsonman/apks/com.google.android.youtube"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
addon-patches = "bin/update-check.mpp"
excluded-patches = "'Custom header for YouTube'"
included-patches = "'Visual preferences icons for YouTube' 'Return YouTube Username'"
patcher-args = "-e Theme -O darkThemeBackgroundColor=#FF121212 -O lightThemeBackgroundColor=#FFF9F9F9 -e 'Custom branding icon for YouTube' -O appIcon=revancify_red -e 'Custom branding name for YouTube' -O appName='RVX YouTube'"

[YouTube-Music-Extended]
enabled = true
app-name = "YouTube Music"
rv-brand = "ReVanced Extended"
build-mode = "both"
arch = "both"
# version = "9.15.51"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/crimsonman/apks/com.google.android.apps.youtube.music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
excluded-patches = "'Custom header for YouTube Music'"
included-patches = "'Disable music video in album' 'Visual preferences icons for YouTube Music' 'Return YouTube Username'"
addon-patches = "bin/update-check.mpp"
patcher-args = "-e 'Custom branding icon for YouTube Music' -O appIcon=revancify_red -e 'Custom branding name for YouTube Music' -O appName='RVX YT Music'"

[YouTube-Morphe]
enabled = true
app-name = "YouTube"
rv-brand = "Morphe"
build-mode = "both"
# version = "21.07.247"
patches-source = "sashade8-ship-it/dual-vot-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/crimsonman/apks/com.google.android.youtube"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
addon-patches = "bin/update-check.mpp"
patcher-args = '-O appIcon=original -e "Custom branding"'

[YouTube-Music-Morphe]
enabled = true
app-name = "YouTube Music"
rv-brand = "Morphe"
build-mode = "both"
arch = "both"
# version = "9.15.51"
patches-source = "MorpheApp/morphe-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/crimsonman/apks/com.google.android.apps.youtube.music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
addon-patches = "bin/update-check.mpp"
patcher-args = '-O appIcon=original -e "Custom branding"'
